# Generated by Django 6.0 on 2026-01-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('heading_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('season_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('goods_name_fa', models.TextField(max_length=1000)),
                ('goods_name_en', models.TextField(max_length=1000)),
                ('profit', models.CharField(max_length=255)),
                ('customs_duty_rate', models.IntegerField(blank=True, null=True)),
                ('import_duty_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('SUQ', models.CharField(choices=[('1000kwh', '1000Kwh'), ('1000u', '1000U'), ('2U', '2U'), ('c', 'C'), ('Carat', 'Carat'), ('Kg', 'Kg'), ('L', 'L'), ('m', 'M'), ('m2', 'M2'), ('m3', 'M3'), ('mm', 'Mm'), ('U', 'U')], default='u', max_length=20)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('heading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hscodes', to='customs.heading')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_seasons', to='customs.season')),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.AddField(
            model_name='heading',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='customs.season'),
        ),
    ]
