# Generated by Django 6.0 on 2026-02-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='SUQ',
            field=models.CharField(choices=[('1000kwh', '1000Kwh'), ('1000u', '1000U'), ('2U', '2U'), ('c', 'C'), ('Carat', 'Carat'), ('Kg', 'Kg'), ('kg', 'Kg'), ('L', 'L'), ('m', 'M'), ('m2', 'M2'), ('m3', 'M3'), ('mm', 'Mm'), ('U', 'U'), ('1000U', '1000U')], default='U', max_length=20),
        ),
    ]
