# Generated by Django 6.0 on 2026-01-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredOrder',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('freight_price', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('sub_total', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('currency_type', models.CharField(default='دلار', max_length=55)),
                ('seller_country', models.CharField(default='asd', max_length=255)),
                ('date', models.CharField(default='2026/01/01', max_length=20)),
                ('expire_date', models.CharField(default='2028/01/01', max_length=20)),
                ('terms_of_delivery', models.CharField(max_length=50)),
                ('terms_of_payment', models.CharField(max_length=50)),
                ('partial_shipment', models.BooleanField(default=False)),
                ('means_of_transport', models.CharField(max_length=50)),
                ('country_of_origin', models.CharField(max_length=555)),
                ('standard', models.CharField(max_length=50)),
                ('total_gw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_nw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('origin', models.CharField(max_length=55)),
                ('unit_price', models.DecimalField(decimal_places=20, default=0, max_digits=40)),
                ('unit', models.CharField(default='U', max_length=55)),
                ('nw_kg', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('gw_kg', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customs.hscode')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.registeredorder')),
            ],
        ),
    ]
