# Generated by Django 6.0 on 2026-02-02 06:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_registeredorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredorder',
            name='order_number',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        )
    ]
