# Generated by Django 6.0 on 2026-02-09 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_ordergood_uuid_registeredorder_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='marketplace.registeredorder'),
        ),
    ]
