# Generated by Django 6.0 on 2026-02-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_registeredorder_created_at_alter_ordergood_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredorder",
            name="verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]

